# Generated by Django 4.2.6 on 2023-10-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Positions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currentPosition", models.CharField(max_length=2)),
                ("targetPosition", models.CharField(max_length=2)),
            ],
        ),
    ]
