# Generated by Django 4.2.6 on 2023-10-28 00:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chess_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Positions",
            new_name="MoveRequest",
        ),
    ]
