# Generated by Django 4.2.6 on 2023-11-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chess_api", "0002_rename_positions_moverequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=2)),
                ("pieceType", models.CharField(max_length=8)),
            ],
        ),
    ]
